Mvc
RayzOnePy/Framework-handmade pull request #2
Opened 2023-11-05 07:12 UTC by RayzOnePy

задание 3 недели(без выполнения тестового задания)

2023-11-05 14:35 UTC, RetmixX requested changes
type

2023-11-05 14:35 UTC, RetmixX commented on project/app/Models/User.php
> +    protected $fillable = [
comment type

2023-11-05 14:35 UTC, RetmixX commented on project/app/Models/User.php
> +    public $timestamps = false;
comment type

2023-11-05 14:35 UTC, RetmixX commented on project/app/Models/User.php
> +    public function findIdentity(int $id)
type

2023-11-05 14:35 UTC, RetmixX commented on project/core/Src/Auth/IdentityInterface.php
> +    public function findIdentity(int $id);
type

2023-11-05 14:35 UTC, RetmixX commented on project/core/Src/Route.php
> +    private $currentHttpMethod;
type

2023-11-05 14:35 UTC, RetmixX commented on project/core/Src/Settings.php
> +    public function getDbSettings()
TYPE!!!!

2023-11-05 14:35 UTC, RetmixX commented on project/core/Src/Validator/AbstractValidator.php
> +    public function validate()
type

2023-11-05 14:35 UTC, RetmixX commented on project/core/Src/View.php
> +        exit();
Чем return не понравился? Зачем сразу делать exit()?

2023-11-05 16:32 UTC, jurapro requested changes
- [x] Исправляй замечания Андрея
- [ ] Реализовывай функционал Гостя из тестового задания

2023-11-05 17:05 UTC, RayzOnePy commented on project/core/Src/View.php
> +        exit();
по методичке же так было

2023-11-07 03:25 UTC, jurapro approved these changes

2023-11-07 08:18 UTC, RayzOnePy commented
вроде сделал функционал гостя, но не уверен что правильно понял что такое функционал гостя.

2023-11-07 08:18 UTC, merged